create table if not exists app_users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null unique,
    password_hash varchar(100) not null,
    enabled boolean not null default true,
    roles varchar(255) not null default 'ROLE_USER',
    created_at timestamp with time zone not null default current_timestamp
);

create table if not exists user_agents (
    id varchar(36) primary key,
    owner_username varchar(100) not null references app_users(username) on delete cascade,
    name varchar(120) not null,
    purpose text not null,
    system_prompt text not null,
    model varchar(200),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint user_agents_owner_name_unique unique (owner_username, name)
);

create index if not exists idx_user_agents_owner on user_agents(owner_username);
