create table if not exists app_users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null unique,
    password_hash varchar(100) not null,
    enabled boolean not null default true,
    roles varchar(255) not null default 'ROLE_USER',
    created_at timestamp with time zone not null default current_timestamp
);
