create table if not exists app_users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null unique,
    password_hash varchar(100) not null,
    enabled boolean not null default true,
    roles varchar(255) not null default 'ROLE_USER',
    created_at timestamp with time zone not null default current_timestamp
);

alter table app_users add column if not exists display_name varchar(200);
alter table app_users add column if not exists email varchar(255);
alter table app_users add column if not exists custom_instructions text;
-- Per-user OpenRouter API key, encrypted at rest (AES-GCM via CredentialCipher). Only ever read back
-- through endpoints scoped to the authenticated user, so one user can never see another's key.
alter table app_users add column if not exists openrouter_api_key_encrypted text;

create table if not exists user_agents (
    id varchar(36) primary key,
    owner_username varchar(100) not null references app_users(username) on delete cascade,
    name varchar(120) not null,
    purpose text not null,
    system_prompt text not null,
    model varchar(200),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint user_agents_owner_name_unique unique (owner_username, name)
);

create index if not exists idx_user_agents_owner on user_agents(owner_username);

create table if not exists openrouter_models (
    id varchar(200) primary key,
    name varchar(200) not null,
    description text,
    context_length bigint,
    prompt_price varchar(64),
    completion_price varchar(64),
    reasoning_options text not null default '[]',
    supported_parameters text not null default '[]',
    updated_at timestamp with time zone not null default current_timestamp
);

create table if not exists user_model_preferences (
    owner_username varchar(100) not null references app_users(username) on delete cascade,
    model_id varchar(200) not null references openrouter_models(id) on delete cascade,
    enabled boolean not null default false,
    updated_at timestamp with time zone not null default current_timestamp,
    primary key (owner_username, model_id)
);

create index if not exists idx_user_model_preferences_owner on user_model_preferences(owner_username);

create table if not exists chat_sessions (
    id varchar(36) primary key,
    owner_username varchar(100) not null references app_users(username) on delete cascade,
    title text,
    mode varchar(32) not null,
    last_event_seq bigint not null default 0,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create index if not exists idx_chat_sessions_owner on chat_sessions(owner_username);

create table if not exists chat_messages (
    id varchar(36) primary key,
    session_id varchar(36) not null references chat_sessions(id) on delete cascade,
    run_id varchar(36),
    role varchar(32) not null,
    content text not null default '',
    status varchar(32) not null,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create index if not exists idx_chat_messages_session_created on chat_messages(session_id, created_at);
create index if not exists idx_chat_messages_run on chat_messages(run_id);

create table if not exists agent_runs (
    id varchar(36) primary key,
    session_id varchar(36) not null references chat_sessions(id) on delete cascade,
    mode varchar(32) not null,
    status varchar(32) not null,
    error_message text,
    started_at timestamp with time zone not null default current_timestamp,
    completed_at timestamp with time zone
);

create index if not exists idx_agent_runs_session_started on agent_runs(session_id, started_at);

create table if not exists chat_events (
    id varchar(36) primary key,
    session_id varchar(36) not null references chat_sessions(id) on delete cascade,
    run_id varchar(36),
    message_id varchar(36),
    seq bigint not null,
    type varchar(64) not null,
    role varchar(32),
    content text,
    metadata text,
    created_at timestamp with time zone not null default current_timestamp,
    constraint uq_chat_events_session_seq unique (session_id, seq)
);

create index if not exists idx_chat_events_session_seq on chat_events(session_id, seq);
create index if not exists idx_chat_events_run_seq on chat_events(run_id, seq);

-- Persistent binding between a GitHub project chat and its cloned-on-disk workspace. The clone lives
-- under $AGENT_HOME/workspace/<repo>-<short-id>/ and survives restarts; this row lets the agent
-- rehydrate the workspace (and re-clone it if the directory was removed) when a chat is resumed long
-- after the in-memory sandbox registration was lost.
create table if not exists github_workspaces (
    sandbox_id varchar(36) primary key,
    repo_full_name varchar(255) not null,
    branch varchar(255),
    clone_url text not null,
    workspace_path text not null,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

-- Isolated, containerized execution environment backing a project (GitHub repository) chat. Each
-- project chat owns exactly one sandbox session: a Docker container plus a named volume holding the
-- repository checkout. This row is the durable handle the backend uses to reconnect to (or clean up)
-- that container across restarts, and to expire it once it has been idle past hugin.sandbox.idle-timeout-hours.
create table if not exists sandbox_sessions (
    id varchar(36) primary key,
    chat_session_id varchar(36),
    container_id text,
    container_name varchar(255),
    docker_volume_name varchar(255),
    repository_url text,
    repository_branch varchar(255),
    repository_path text,
    status varchar(32) not null,
    created_at timestamp with time zone not null default current_timestamp,
    last_used_at timestamp with time zone not null default current_timestamp,
    expires_at timestamp with time zone
);

create index if not exists idx_sandbox_sessions_chat on sandbox_sessions(chat_session_id);
create index if not exists idx_sandbox_sessions_expires on sandbox_sessions(expires_at);
